### ISSUE TITLE
Thème perso avec charte graphique France Insoumise

### ISSUE THREAD

**Issue by lucasgautheron** [lucasgautheron/tribune.insoumis.online#1]
* Bleu : #0e8a9c
 * orange : #e23d22
 * Police : ~~Monteserrat~~ Roboto Slab
 * ```text-align: justify``` pour les articles (done) avec un custom.css

Génération des fichiers à placer dans /themes/fi:
http://getbootstrap.com/customize/

@font-family-serif = "Roboto Slab", serif
@font-family-base = @font-family-serif

FIXME: apparemment les CSS ne correspondent pas à ce que themes/fi contient... à l'aide!

**Comment by lucasgautheron** [comment]
@Thomas-Darion ça t'intéresses ? :)

**Comment by Thomas-Darion** [comment]
@lucasgautheron Salut, que me demandes tu exactement ? générer un css via Bootstrap et remplacer les existants ?

**Comment by lucasgautheron** [comment]
@Thomas-Darion voilà :) j'ai résolu l'autre partie du problème.
tu peux passer sur le discord ?

**Comment by lucasgautheron** [comment]
Je ferme, si vous avez des idées en + faîtes un nouveau ticket
