### ISSUE TITLE
Adresse email de contact ?

### ISSUE THREAD

**Issue by lucasgautheron** [lucasgautheron/tribune.insoumis.online#2]
En existe-t-il une ?

**Comment by LucileDT** [comment]
Si c'est pour moi, je crois que Topper en a mis une en place, et sinon pour l'instant ya pas de smtp sur servenchon donc pas de mail vraiment à nous.

**Comment by lucasgautheron** [comment]
OK. Il en faudrait une pour les curieux, les retours quelconques, ou la presse :)

**Comment by LucileDT** [comment]
@TopperFr Pourrais-tu jeter un oeil ici stp ?
